// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuLwYd_KzTZ1be7IuX67yBiCbkEBAqWD8',
    appId: '1:755090540780:web:37c278d769617a7ee9fdc9',
    messagingSenderId: '755090540780',
    projectId: 'newprogress-financr',
    authDomain: 'newprogress-financr.firebaseapp.com',
    storageBucket: 'newprogress-financr.appspot.com',
    measurementId: 'G-PRWRYE730E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9PXtCfd5f3ixIKJNT6emnWVJhLT5wHrs',
    appId: '1:755090540780:android:fed744308fd749bde9fdc9',
    messagingSenderId: '755090540780',
    projectId: 'newprogress-financr',
    storageBucket: 'newprogress-financr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa0osZuXeqqeL7rh3ngpLv9xqrmU3Lf6Q',
    appId: '1:755090540780:ios:dcc86933ad95847ce9fdc9',
    messagingSenderId: '755090540780',
    projectId: 'newprogress-financr',
    storageBucket: 'newprogress-financr.appspot.com',
    iosBundleId: 'com.example.npFinancr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa0osZuXeqqeL7rh3ngpLv9xqrmU3Lf6Q',
    appId: '1:755090540780:ios:f1092cfb4aadee74e9fdc9',
    messagingSenderId: '755090540780',
    projectId: 'newprogress-financr',
    storageBucket: 'newprogress-financr.appspot.com',
    iosBundleId: 'com.example.npFinancr.RunnerTests',
  );
}
